#!/bin/sh
NAME=husby

case "$1" in
    start)
        /usr/bin/psplash-write "PROGRESS 10"
        sleep 1
        /usr/bin/psplash-write "PROGRESS 30"
        sleep 1
        /usr/bin/psplash-write "PROGRESS 50"
        sleep 1
        /usr/bin/psplash-write "PROGRESS 70"
        sleep 1
        /usr/bin/psplash-write "PROGRESS 90"
        sleep 1
        /usr/bin/psplash-write "PROGRESS 100"
        ;;
    stop)
        exit 1
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 1
        ;;
esac