#!/bin/sh
NAME=husby

case "$1" in
    start)
        sleep 5
        /usr/bin/psplash-write "QUIT"
        ;;
    stop)
        exit 1
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 1
        ;;
esac