name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: crust.pkr.hcl

      # init project
      - name: Init Project
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: crust.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: crust.pkr.hcl
        env:
          PACKER_LOG: 1

      # archive artifact
      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Crust
          path: output-raspbian/image