name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # packer installation
      - name: Install Packer
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && sudo apt-get update && sudo apt-get install packer

      # tool installation
      - name: Install Tools
        run: sudo apt update && sudo apt install git wget zip unzip build-essential kpartx qemu binfmt-support qemu-user-static e2fsprogs dosfstools
     
      # init project
      - name: Init Project
        run: packer init crust.pkr.hcl

      # validate templates
      - name: Validate Template
        run: packer validate crust.pkr.hcl

      # build artifact
      - name: Build Artifact
        run: sudo packer build crust.pkr.hcl

      # zip artifact
      - name: Zip Artifact
        run: zip -r rpi-crust.zip output-raspbian/image 

      # archive artifact
      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Crust
          path: rpi-crust.zip